// Generated by Dagger (https://dagger.dev).
package com.microsoft.teams.sdk.rnbundle;

import com.microsoft.teams.core.app.ITeamsApplication;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SdkCodepushBundleDownloader_Factory implements Factory<SdkCodepushBundleDownloader> {
  private final Provider<ITeamsApplication> teamsApplicationProvider;

  private final Provider<ISdkBundleManager> sdkBundleManagerProvider;

  public SdkCodepushBundleDownloader_Factory(Provider<ITeamsApplication> teamsApplicationProvider,
      Provider<ISdkBundleManager> sdkBundleManagerProvider) {
    this.teamsApplicationProvider = teamsApplicationProvider;
    this.sdkBundleManagerProvider = sdkBundleManagerProvider;
  }

  @Override
  public SdkCodepushBundleDownloader get() {
    return newInstance(teamsApplicationProvider.get(), sdkBundleManagerProvider.get());
  }

  public static SdkCodepushBundleDownloader_Factory create(
      Provider<ITeamsApplication> teamsApplicationProvider,
      Provider<ISdkBundleManager> sdkBundleManagerProvider) {
    return new SdkCodepushBundleDownloader_Factory(teamsApplicationProvider, sdkBundleManagerProvider);
  }

  public static SdkCodepushBundleDownloader newInstance(ITeamsApplication teamsApplication,
      ISdkBundleManager sdkBundleManager) {
    return new SdkCodepushBundleDownloader(teamsApplication, sdkBundleManager);
  }
}
