// Generated by Dagger (https://dagger.dev).
package com.microsoft.teams.sdk.rnbundle;

import com.microsoft.teams.storage.dao.rnbundles.RNBundlesDao;
import com.microsoft.teams.core.app.ITeamsApplication;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SdkBundleManager_Factory implements Factory<SdkBundleManager> {
  private final Provider<ITeamsApplication> teamsApplicationProvider;

  private final Provider<RNBundlesDao> rnBundlesDaoProvider;

  public SdkBundleManager_Factory(Provider<ITeamsApplication> teamsApplicationProvider,
      Provider<RNBundlesDao> rnBundlesDaoProvider) {
    this.teamsApplicationProvider = teamsApplicationProvider;
    this.rnBundlesDaoProvider = rnBundlesDaoProvider;
  }

  @Override
  public SdkBundleManager get() {
    return newInstance(teamsApplicationProvider.get(), rnBundlesDaoProvider.get());
  }

  public static SdkBundleManager_Factory create(
      Provider<ITeamsApplication> teamsApplicationProvider,
      Provider<RNBundlesDao> rnBundlesDaoProvider) {
    return new SdkBundleManager_Factory(teamsApplicationProvider, rnBundlesDaoProvider);
  }

  public static SdkBundleManager newInstance(ITeamsApplication teamsApplication,
      RNBundlesDao rnBundlesDao) {
    return new SdkBundleManager(teamsApplication, rnBundlesDao);
  }
}
