// Generated by Dagger (https://dagger.dev).
package com.microsoft.teams.sdk.rnbundle;

import com.microsoft.teams.core.app.ITeamsApplication;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SdkLocalBundleDownloader_Factory implements Factory<SdkLocalBundleDownloader> {
  private final Provider<ITeamsApplication> teamsApplicationProvider;

  public SdkLocalBundleDownloader_Factory(Provider<ITeamsApplication> teamsApplicationProvider) {
    this.teamsApplicationProvider = teamsApplicationProvider;
  }

  @Override
  public SdkLocalBundleDownloader get() {
    return newInstance(teamsApplicationProvider.get());
  }

  public static SdkLocalBundleDownloader_Factory create(
      Provider<ITeamsApplication> teamsApplicationProvider) {
    return new SdkLocalBundleDownloader_Factory(teamsApplicationProvider);
  }

  public static SdkLocalBundleDownloader newInstance(ITeamsApplication teamsApplication) {
    return new SdkLocalBundleDownloader(teamsApplication);
  }
}
