### YamlMime:UniversalReference
items:
  - uid: teams-mobile-sdk.ConfigurationInterface
    name: ConfigurationInterface
    fullName: ConfigurationInterface
    children:
      - teams-mobile-sdk.ConfigurationInterface.setAriaTenant
    langs:
      - typeScript
    type: interface
    summary: ''
    package: teams-mobile-sdk
  - uid: teams-mobile-sdk.ConfigurationInterface.setAriaTenant
    name: setAriaTenant(string)
    children: []
    type: method
    langs:
      - typeScript
    summary: ''
    syntax:
      content: 'function setAriaTenant(tenantToken: string)'
      parameters:
        - id: tenantToken
          type:
            - string
          description: ''
      return:
        type:
          - any
    package: teams-mobile-sdk
