// Generated by Dagger (https://dagger.dev).
package com.microsoft.teams.mobilemodules;

import com.microsoft.hubapphost.impls.TeamsSdkSimPlatformAppFactory;
import com.microsoft.teams.sdk.ISdkRunnerAppManager;
import com.microsoft.teams.storage.dao.appdefinition.AppDefinitionDao;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PlatformAppManager_Factory implements Factory<PlatformAppManager> {
  private final Provider<TeamsSdkSimPlatformAppFactory> platformAppFactoryProvider;

  private final Provider<ISdkRunnerAppManager> sdkRunnerAppManagerProvider;

  private final Provider<AppDefinitionDao> appDefinitionDaoProvider;

  public PlatformAppManager_Factory(
      Provider<TeamsSdkSimPlatformAppFactory> platformAppFactoryProvider,
      Provider<ISdkRunnerAppManager> sdkRunnerAppManagerProvider,
      Provider<AppDefinitionDao> appDefinitionDaoProvider) {
    this.platformAppFactoryProvider = platformAppFactoryProvider;
    this.sdkRunnerAppManagerProvider = sdkRunnerAppManagerProvider;
    this.appDefinitionDaoProvider = appDefinitionDaoProvider;
  }

  @Override
  public PlatformAppManager get() {
    return newInstance(platformAppFactoryProvider.get(), sdkRunnerAppManagerProvider.get(), appDefinitionDaoProvider.get());
  }

  public static PlatformAppManager_Factory create(
      Provider<TeamsSdkSimPlatformAppFactory> platformAppFactoryProvider,
      Provider<ISdkRunnerAppManager> sdkRunnerAppManagerProvider,
      Provider<AppDefinitionDao> appDefinitionDaoProvider) {
    return new PlatformAppManager_Factory(platformAppFactoryProvider, sdkRunnerAppManagerProvider, appDefinitionDaoProvider);
  }

  public static PlatformAppManager newInstance(TeamsSdkSimPlatformAppFactory platformAppFactory,
      ISdkRunnerAppManager sdkRunnerAppManager, AppDefinitionDao appDefinitionDao) {
    return new PlatformAppManager(platformAppFactory, sdkRunnerAppManager, appDefinitionDao);
  }
}
